language: node_js
node_js:
  - 6.9.1
before_script:
  - npm install
deploy:
  provider: bluemixcloudfoundry
  skip_cleanup: true
  manifest: manifest.yml
  username: yuribarssi@gmail.com
  password: $BLUEMIX_PASS
  organization: barssicorp
  space: bimrooms
  api: https://api.eu-de.bluemix.net
  on:
    branch: master
