language: node_js
node_js:
  - 6.9.1
before_script:
  - npm install
deploy:
  provider: bluemixcloudfoundry
  skip_cleanup: true
  manifest: manifest.yml
  username: yuribarssi@gmail.com
  password: bim00bim
  organization: my_organization
  space: my_space
  on:
    branch: master
